import tkinter
from tkinter import ttk
from PIL import Image
from PIL import ImageTk

window = tkinter.Tk()

window.geometry("910x480")
window.title("Senior Project")
rows =0
while rows<50:
    window.rowconfigure(rows,weight=1)
    window.columnconfigure(rows,weight=1)
    rows += 1
nb = ttk.Notebook(window)
nb.grid(row=1,column=0,columnspan=50,rowspan=49,sticky="NESW")
page1 = ttk.Frame(nb)
nb.add(page1,text="Shortcuts")
page2 = ttk.Frame(nb)
nb.add(page2,text="Settings")
page3 = ttk.Frame(nb)
nb.add(page3,text="About us")
page4 = ttk.Frame(nb)
nb.add(page4,text="Hand Settings")
backgroundimage1 = Image.open("D:/lectures/gradiant_background.jpg")
backgroundImage = ImageTk.PhotoImage(backgroundimage1)
#window.configure(background="black")
C = tkinter.Label(page4,image=backgroundImage)
C.place(relx=.5,rely=.5,anchor="center")
C.lower()
C.rowconfigure(0, weight=100)
C.rowconfigure(3, weight=100)
C.columnconfigure(0, weight=100)
C.columnconfigure(3, weight=100)
C = tkinter.Label(page2,image=backgroundImage)
C.place(relx=.5,rely=.5,anchor="center")
C.lower()
C.rowconfigure(0, weight=100)
C.rowconfigure(3, weight=100)
C.columnconfigure(0, weight=100)
C.columnconfigure(3, weight=100)
C = tkinter.Label(page3,image=backgroundImage)
C.place(relx=.5,rely=.5,anchor="center")
C.lower()
C.rowconfigure(0, weight=100)
C.rowconfigure(3, weight=100)
C.columnconfigure(0, weight=100)
C.columnconfigure(3, weight=100)
C = tkinter.Label(page1,image=backgroundImage)
C.place(relx=.5,rely=.5,anchor="center")
C.lower()
C.rowconfigure(0, weight=100)
C.rowconfigure(3, weight=100)
C.columnconfigure(0, weight=100)
C.columnconfigure(3, weight=100)
C = tkinter.Label(page4,image=backgroundImage)
img1 = Image.open("D:/lectures/hand1.PNG")
img1 = img1.resize((100,100))
new_img1 = ImageTk.PhotoImage(img1)
img2 = Image.open("D:/lectures/wavehand.png").convert("RGBA")
img2 = img2.resize((100,100),Image.ANTIALIAS)
new_img2 = ImageTk.PhotoImage(img2)
img3 = Image.open("D:/lectures/wavemove.png").convert("RGBA")
img3 = img3.resize((100,100),Image.ANTIALIAS)
new_img3 = ImageTk.PhotoImage(img3)
AIU_logo = Image.open("D:/lectures/220px-Arab_International_University_logo.png")
AIU_logo = AIU_logo.resize((200,200),Image.ANTIALIAS)
new_AIU_logo = ImageTk.PhotoImage(AIU_logo)
#label1 = tkinter.Label(window,text = "Hand Gesturing",font = ("arial",16,"bold")).grid(row=0,column=22)
Label2 = tkinter.Button(page1,text = "Hand1",image = new_img1,bg="#282c31",font=("arial",16,"bold"),borderwidth=0)
Label3 = tkinter.Label(page1,text="hand2",image = new_img2,bg="#212529",font=("arial",16,"bold"))
Label4 = tkinter.Label(page1,text="Hand2",image = new_img3,fg="white",bg="black",font=("arial",16,"bold"))
AIULOGOLABEL = tkinter.Label(page3,image= new_AIU_logo,text="Aiulolo",bg="#1d2024")
Label2.grid(row=10)
Label3.grid(row=11)
Label4.grid(row=12)
AIULOGOLABEL.place(relx=.4,rely=.5)
e1 = tkinter.Entry(page1)
e2 = tkinter.Entry(page1)
e3 = tkinter.Entry(page1)
e1.grid(row=10,column=1)
e2.grid(row=11,column=1)
e3.grid(row=12,column=1)
StartButton = tkinter.Button(page1,text="Start",height=2,width=5,font="bold",borderwidth=4).grid(row=35,column=1)
QuitButton = tkinter.Button(page1,text="Quit",height=2,width=5,command=window.destroy,font="bold",borderwidth="4").grid(row=35,column=0)
e1.insert(10,"www.facebook.com")
e2.insert(10,"www.google.com")
e3.insert(10,"www.youtube.com")
scale1 = tkinter.Scale(page2,from_=0, to=5,orient=tkinter.HORIZONTAL,bg="#282c31",length=200,label="Mouse Sensivity",fg="white").grid(row=2,column=0)
scale2 = tkinter.Scale(page2,from_=0, to=5,orient=tkinter.HORIZONTAL,bg= "#212529",length=200,label="Smoothnes",fg="white").grid(row=10,column=0)
scale3 = tkinter.Scale(page2,from_=0, to=5,orient=tkinter.HORIZONTAL,bg="#1f2226",length=200,label="Accuracy",fg="white").grid(row=18,column=0)

LeftorRight = tkinter.StringVar()
LeftorRight.set("Left")
LeftRadioButton1 = tkinter.Radiobutton(page2,text="Left Hand",variable=LeftorRight,value="left",bg="#1f2226",fg="white").place(relx=.0,rely=.5)
LeftRadioButton2 = tkinter.Radiobutton(page2,text="Right Hand",variable=LeftorRight,value="right",bg="#1f2226",fg="white").place(relx=.1,rely=.5)
RecognizeButton = tkinter.Button(page2,text="Recognize Move",height=2,width=15,font=("arial",10,"bold"),borderwidth="4").place(relx=.0,rely=.4) #grid(row=26,column=0)
NewPalmButton = tkinter.Button(page2,text="New Palm",height=2,width=15,font=("arial",10,"bold"),borderwidth="4").place(relx=.2,rely=.4) #grid(row=26,column=4)
Aman = tkinter.Label(page3,text="Aman Safadi",font=("arial",15,"bold"),fg="white",bg="#282c31").place(relx=0.43,rely=0.1)
Omar = tkinter.Label(page3,text="Omar Aboulabdeh",font=("arial",15,"bold"),fg="white",bg="#282c31").place(relx=0.43,rely=0.2)
Aboud = tkinter.Label(page3,text="Abdallah Madani",font=("arial",15,"bold"),fg="white",bg="#282c31").place(relx=0.43,rely=0.3)
Alaa = tkinter.Label(page3,text="Alaa AlHafez",font=("arial",15,"bold"),fg="white",bg="#282c31").place(relx=0.43,rely=0.4)
window.mainloop()